name: Run Macro Pipeline

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    # ESTO ES VITAL: Le dice a GitHub que este trabajo TIENE permiso de escribir
    permissions:
      contents: write

    steps:
      - name: Descargar repo
        uses: actions/checkout@v4
        with:
          # Usamos el token automático del sistema
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar librerías
        run: |
          pip install pandas yfinance requests openpyxl lxml

      - name: Ejecutar script
        run: python macro_pipeline.py

      - name: Guardar Cambios
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-update: $(date +'%Y-%m-%d')"
          file_pattern: 'Macro_Master_Historico.xlsx'
          # Esto ayuda a que no se pelee con permisos de usuario
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
